# Generated by Django 4.2.7 on 2023-12-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='deadline',
            field=models.CharField(max_length=250),
        ),
    ]
